config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    resources :user_preferences, only: [:index, :show, :new, :create, :edit, :update]
  end
  resources :organizations
  resources :dogs
  resources :matches, only: [:index, :show, :new]
  resources :chatrooms, only: [:index, :show, :new, :create, :destroy] do
    resources :messages, only: :create
  end

  resources :contacts, only: [:new, :create ]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get 'contacts/sent'
  put "/dog/:id/like", to: "dogs#like", as: "like"
  put "/dog/:id/dislike", to: "dogs#dislike", as: "dislike"
  get "/user/:id/my+likes", to: "users#my_likes", as: "my_likes"
  get "/user/:id/my+preferences", to: "users#my_preferences", as: "my_preferences"






  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-last.png", alt: 'Application Logo', style: 'height: 45px; width: 150px' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Find a Match", matches_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dogs", dogs_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Organizations", organizations_path, class: "nav-link" %>
          </li>


          <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
            <%= image_tag "user-placeholder.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "My Likes", my_likes_path(current_user), class: "dropdown-item" %>
              <% if current_user.organization != nil %>
              <%= link_to "My Organization", organization_path(current_user.organization), class: "dropdown-item" %>
              <% else %>
              <%= link_to "Create an Organization", new_organization_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "My Messages", chatrooms_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out",  destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
        <li class="nav-item"-->
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <%  end %>
      </ul>
    </div>
  </div>
</div>