config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    resources :user_preferences, only: [:index, :show, :new, :create, :edit, :update]
  end
  resources :organizations
  resources :dogs
  resources :matches, only: [:index, :show, :new]
  resources :chatrooms, only: [:index, :show, :new, :create, :destroy] do
    resources :messages, only: :create
  end

  resources :contacts, only: [:new, :create ]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get 'contacts/sent'
  put "/dog/:id/like", to: "dogs#like", as: "like"
  put "/dog/:id/dislike", to: "dogs#dislike", as: "dislike"
  get "/user/:id/my+likes", to: "users#my_likes", as: "my_likes"
  get "/user/:id/my+preferences", to: "users#my_preferences", as: "my_preferences"






  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/match.rb
class Match < ApplicationRecord
  has_one :dog
  has_one :user
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    # Setting the user
    @user = current_user
    @dogs = Dog.where(adopted: false)
    @new_dogs = []

    @dogs.each do |dog|
      if dog.liked?(current_user) == false && dog.disliked?(current_user) == false
        @new_dogs.push(dog)
      end

      if @user.user_preference
        if dog.gender != @user.user_preference.gender && @user.user_preference.gender != nil
          @new_dogs.delete(dog)
        elsif dog.vaccinated != @user.user_preference.vaccinated && @user.user_preference.vaccinated != 'No Preference'
          @new_dogs.delete(dog)
        elsif dog.neutered != @user.user_preference.neutered && @user.user_preference.neutered != nil
          @new_dogs.delete(dog)
        elsif @user.user_preference.age_category && dog.age_category != @user.user_preference.age_category
          @new_dogs.delete(dog)
        end
      else
        @new_dogs = @dogs.select do |dog|
          !dog.liked?(current_user) && !dog.disliked?(current_user)
        end
      end
    end

    @dog = @new_dogs.sample if @new_dogs.any?
  end
end

app/views/matches/_dog_card.html.erb
    <div class="row">


            <div class="col-lg-4 col-md-6 col-sm-6 mb-3" style='margin: auto'>
              <div class="card h-100">
              <%= link_to dog_path(@dog) do %>
                <% if @dog.photo.attached? %>
                <%= cl_image_tag @dog.photo.key, crop: :fill, class: "card-img-top" %>
                <% else %>
                <%= image_tag 'missing-image.png', class: 'card-img-top' %>
                <% end %>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title text-center"> <%= @dog.name %> </h5>
                  <p class="card-text text-justify"> <%= @dog.description %></p>

                  <div class="text-center d-flex justify-content-center">
              <%= button_to like_path(@dog), class: 'like-button', style: 'margin: 1rem', method: 'put' do %>
              <i class="match-liked fa-solid fa-check" style='padding: 0.5rem; border-radius: 50%';></i>
              <% end %>
              <%= button_to dislike_path(@dog), class: 'like-button', style: 'margin: 1rem', method: 'put' do %>
              <i class="match-disliked fa-sharp fa-solid fa-xmark" style='padding: 0.5rem 0.7rem; border-radius: 50%';></i>
              <% end %>
                  </div>
                  </div>
                </div>
              </div>
            </div>
    </div>

</div>

app/views/matches/_empty_card.html.erb
    <div class="row">

            <div class="col-lg-4 col-md-6 col-sm-6 mb-3" style='margin: auto'>
              <div class="card h-100">
                <div class="card-body">
                  <h5 class="card-title text-center"> Too bad! </h5>
                    <%= image_tag 'missing-image.png', class: 'card-img-top' %>
                  <p class="text-justify"> No dogs are matching your preferences.
                  Edit your preferences or browse all the available dogs to find your perfect match! </p>

                  <div class="text-center d-flex justify-content-center">

              <%= link_to 'Browse Dogs', dogs_path, class: 'btn btn-flat', style: 'margin: 2px' %>
              <%= link_to 'Edit Preferences', edit_user_user_preference_path(current_user, current_user.user_preference), class: 'btn btn-flat', style: 'margin: 2px' %>

                  </div>
                  </div>
                </div>
              </div>
            </div>
    </div>

</div>

app/views/matches/index.html.erb
<div style='background-color: #E8CFC1; height: 100%'>
  <div class="container" style='padding: 2rem 0;'>
    <div  style='margin: auto'>
    <h2 class='text-center'>Welcome to our <span style='font-weight: bold; color: #e86048;'> Adoption Match</span>!</h2>
    <h5 class='text-center'>A tool designed to help you find your perfect Heart Dog.</h5>

   <!-- Button trigger modal -->
   <div class="text-center m-2 p-4">
<button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#exampleModal">
  How does it work?
</button>
<% if current_user.user_preference.nil? %>
<%= link_to 'Set my Preferences', new_user_user_preference_path(current_user), class: 'btn btn-flat' %>
<% else %>
<%= link_to 'Edit my Preferences', edit_user_user_preference_path(current_user, current_user.user_preference), class: 'btn btn-flat' %>
<% end %>



</div>

<!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">How Does it Work?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
           <p style='font-weight:bold;'>What is the Adoption Match?</p>
                  <p style='color: #5A5A5A'>Adoption Match is a tool designed to help you find the perfect dog. Both organizations and potential adopters will provide their preferences. When a match is found, the dog will be shown on this page. </p>

            <p style='font-weight:bold;'>Refine Your Search</p>
                  <p style='color: #5A5A5A'>Use the "Edit my Preferences" button tell us what you are looking for.</p>

            <p style='font-weight:bold'>Yes or Next</p>
                  <p style='color: #5A5A5A'>Is this the puppy of your dreams? Then press the 'Contact' button to ask for more information, or 'Like' the profile to save it in your account. Not a match? Next! </p>


          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-flat" data-bs-dismiss="modal">Let's Do It!</button>
          </div>
        </div>
      </div>
    </div>
    <% if @new_dogs.empty? %>
    <%= render "empty_card" %>
    <% else %>
    <%= render "dog_card", dog: @dog %>
    <% end %>


    </div>
  </div>
</div>

app/views/matches/show.html.erb
Hello from show.html.erb

<%= @dog.name %>