config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    resources :user_preferences, only: [:index, :show, :new, :create, :edit, :update]
  end
  resources :organizations
  resources :dogs
  resources :matches, only: [:index, :show, :new]
  resources :chatrooms, only: [:index, :show, :new, :create, :destroy] do
    resources :messages, only: :create
  end

  resources :contacts, only: [:new, :create ]
  get '/contacts', to: 'contacts#new', as: 'contact'
  get 'contacts/sent'
  put "/dog/:id/like", to: "dogs#like", as: "like"
  put "/dog/:id/dislike", to: "dogs#dislike", as: "dislike"
  get "/user/:id/my+likes", to: "users#my_likes", as: "my_likes"
  get "/user/:id/my+preferences", to: "users#my_preferences", as: "my_preferences"






  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_many :dogs
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController


  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR city ILIKE :query"
      @organizations = Organization.where(sql_query, query: "%#{params[:query]}%")
      @markers = @organizations.geocoded.map do |organization|
        {
          lat: organization.latitude,
          lng: organization.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: { organization: organization })
        }
      end
    else
      @organizations = Organization.all
      @markers = @organizations.geocoded.map do |organization|
        {
          lat: organization.latitude,
          lng: organization.longitude,
          info_window_html: render_to_string(partial: "info_window", locals: { organization: organization })
        }
      end
    end
  end


  def show
    @organization = Organization.find(params[:id])
    @owner = @organization.user
    @available_dogs = @organization.dogs.where(adopted: false)

  end

  def new
    @organization = Organization.new
  end

  def create
    params = organization_params
    params[:user] = current_user
    @organization = Organization.new(params)
    @organization.save!
    redirect_to organization_path(@organization)
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    @organization.update(organization_params)
    redirect_to organization_path(@organization)
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy
    redirect_to organizations_path, status: :see_other
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :description, :user, :address, :city, :whatsapp, :email, :website, :photo)
  end

end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :whatsapp, :label => "Whatsapp Number"  %>
  <%= f.input :email, :label => "Email Address", pattern: "[a-zA-Z]+" %>
  <%= f.input :website %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>

   <div class="form-actions" style='text-align: center'>
    <%= f.button :submit, "Submit", class: 'btn btn-flat' %>
  </div>

<% end %>

app/views/organizations/_info_window.html.erb
<h2><%= organization.name %></h2>
<p><%= organization.address%>, <%=organization.city %></p>
<% if organization.dogs.where(adopted:false).count == 1 %>
<p> <strong> <%= organization.dogs.where(adopted: false).count %></strong> pet is currently up for adoption at this location.</p>
<% else %>
<p> <strong> <%= organization.dogs.where(adopted: false).count %></strong> pets are currently up for adoption at this location.</p>
<% end %>
<%= link_to 'Learn more', organization_path(organization), style: 'border: none; text-decoration: none;' %>

app/views/organizations/edit.html.erb
<div style='background-color: #E8CFC1; height: 100%; min-height: 100vh;'>
  <div class="container" style='padding: 100px 0; width: 50%;'>
    <div style='text-align: center; padding-bottom: 20px'>
    <h2>Update your <span style='font-weight: bold; color: #e86048;'> Profile</span></h2>
    <h5> Make sure your information is always up to date. </h5>
    </div>
    <%= render "form", organization: @organization %>
  </div>
</div>

app/views/organizations/index.html.erb
<div style='background-color: #E8CFC1; height: 100%'>
  <div class="container" style='padding: 2rem 0;'>
    <div  style='padding: 2rem'>
    <h2 class='text-center'>Meet our <span style='font-weight: bold; color: #e86048;'> Rescuers</span> </h2>
    <h5 class='text-center'> Find out more about the heroes that saved the lives of our pups.  </h5>
    </div>


<!-- Search -->


<div class="row">
   <div class="col-lg-3 col-md-3 col-sm-3 text-center">
   </div>

    <div class="col-lg-6 col-md-6 col-sm-6 mb-3 text-center">
      <%= form_with url: organizations_path, method: :get, class: "d-flex input-group rounded" do %>

        <%= text_field_tag :query,
          params[:query],
          class: "form-control rounded",
          placeholder: "Enter a name or a city..." %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>

     <div class="col-lg-3 col-md-3 col-sm-3 mb-3 text-center">
   </div>


<!-- Map -->

  <div class="row" style='margin: 0; padding: 0;'>
   <div class="col text=center">

    <div style="width: 100%; height: 400px; margin-bottom: 20px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
      </div>

  <!-- [...] -->

        <% @organizations.each do |organization| %>
            <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
              <div class="card h-100 ">
               <% if organization.photo.attached? %>
                <%= cl_image_tag organization.photo.key, crop: :fill, class: "card-img-top" %>
                <% else %>
                <%= image_tag 'missing-image.png', class: 'card-img-top' %>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title text-center"> <%= organization.name %> </h5>
                  <p class="card-text text-justify text-truncate"> <%= organization.description %></p>
                  <div class="text-center">
                    <%= link_to "Find Out More", organization_path(organization), class: "btn btn-flat" %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
Hello new

app/views/organizations/show.html.erb
<div style='background-color: #E8CFC1; height: 100%'>
<div class="container">

<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-size: cover; background-image: url('https://images.unsplash.com/photo-1542715234-4bafcfc68bd9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80'); background-position: center; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
            <% if @organization.photo.attached? %>
                 <%= cl_image_tag @organization.photo.key, height: 150, style: 'z-index: 1',  crop: :fill,  class: "img-fluid img-thumbnail mt-4 mb-2" %>
                 <% else %>
                <%= image_tag 'missing-image.png', class: 'mg-fluid img-thumbnail mt-4 mb-2', style: 'width: 150px; z-index: 1;' %>
                <% end %>
                <% if current_user == @organization.user %>
                <%= link_to "Edit", edit_organization_path(@organization), class: "btn btn-flat", style: "z-index: 1;" %>
                <% else %>
               <%= link_to "Chat", new_chatroom_path(chat_user: @organization.user), class: "btn btn-flat", style: "z-index: 1;" %>
                <% end %>

            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h5 style='color: white; font-weight: bold;';><%= @organization.name%></h5>
              <p> <%= @organization.address%>, <%= @organization.city%> </p>
            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-end text-center py-1">
              <div>
                <p class="mb-1 h5"><%= @organization.dogs.count %></p>
                <p class="small text-muted mb-0">Dogs</p>
              </div>
              <div class="px-3">

              </div>
              <div>
                  <p class="mb-1 h5"><%= @organization.dogs.where(adopted: "true").count %></p>
                <p class="small text-muted mb-0">Adoptions</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">About</p>
              <div class="p-4" style="background-color: #f8f9fa;">
                 <p class="font-italic mb-1"> <%=  @organization.description %></p>
              </div>
            </div>
            <div class="mb-5">
              <p class="lead fw-normal mb-1">Get in Touch</p>
              <div class="p-4">
              <ul class="list-group w-100 mx-auto">
                <div class="list-group-item">
                <span class="d-inline-flex align-items-center justify-content-center text-white rounded m-1 me-2" style="background-color: #0082ca; width: 40px; height: 40px;">
                  <i class="fab fa-whatsapp fa-lg"></i>
                </span>
                <%= @organization.whatsapp %>
              </div>
              <div class="list-group-item">
                <div class="d-inline-flex align-items-center justify-content-center text-white rounded m-1 me-2" style="background-color: #ff4500; width: 40px; height: 40px;">
                  <i class="fas fa-envelope fa-lg"></i>
                </div>
                <%= @organization.email %>
              </div>
              <div class="list-group-item">
                <div class="d-inline-flex align-items-center justify-content-center text-white rounded m-1 me-2" style="background-color: #00b386; width: 40px; height: 40px;">
                  <i class="fas fa-laptop fa-lg"></i>
                </div>
                <%= @organization.website %>
              </div>
            </ul>

              </div>
            </div>
            <div class="mb-5">
            <div.d-flex
>
              <div class='d-flex justify-content-between'>
              <p class="lead fw-normal mb-1">Available Dogs </p>
              <% if current_user.organization == @organization %>
                <p><%= link_to "Add +", new_dog_path, class: "btn btn-flat", style: "margin: 0; background-color: #00b386;" %> </p>
              <% else %>
              <div ></div>
              <% end %>
              </div>

              <div class="row row-cols-1 row-cols-md-3">
            <% @available_dogs.each do |dog| %>
            <div class="col-lg-6 col-md-6 col-sm-6 mb-3">
              <div class="card h-100">
                <% if dog.photo.attached? %>
                <%= cl_image_tag dog.photo.key, crop: :fill, class: "card-img-top" %>
                <% else %>
                <%= image_tag 'missing-image.png', class: 'card-img-top'  %>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title text-center"> <%= dog.name %> </h5>
                  <p class="card-text text-justify"> <%= dog.description %></p>
                  <div class="text-center">
                     <% if current_user == @organization.user %>
                    <%= link_to "View", dog_path(dog), class: "btn btn-flat" %>
                    <%= link_to "Edit", edit_dog_path(dog), class: "btn btn-flat" %>
                    <% else %>
                   <%= link_to "Find Out More", dog_path(dog), class: "btn btn-flat" %>
                   <% end %>


                  </div>


                </div>
              </div>
            </div>
        <% end %>
    </div>

          <div class='text-center m-4'>
             <%= link_to 'Back', :back , class: "btn btn-flat" %>
           </div>
              </div>



          </div>
        </div>
      </div>
    </div>
  </div>
</section>



</div>
</div>